### ISSUE TITLE
Bulk send

### ISSUE THREAD

**Issue by juggernautt** [oanhnn/laravel-logzio#2]
Can you please explain what should I do in order to send several logs at once. What's the format?

**Comment by oanhnn** [comment]
1. This solution using [bulk upload JSON logs over HTTP/HTTPS](https://docs.logz.io/shipping/log-sources/json-uploads.html)
2. Log format using `\Laravel\Logzio\Log\Formatter`. It will convert your log records to JSON logs, seperated by a new line. And handler will send Logz.io server.
   ```
   {"message": "Hello there", "level": 200, "level_name": "INFO", "channel": "test-log", "@timestamp": "2019-11-06T08:11:05+00:00"}
   {"message": "Hello again", "level": 200, "level_name": "INFO", "channel": "test-log", "@timestamp": "2019-11-06T08:11:06+00:00"}
   ```
