### ISSUE TITLE
Missing Region

### ISSUE THREAD

**Issue by fred-cardoso** [oanhnn/laravel-logzio#6]
Hi!

I created a new account that the endpoint is `https://listener-uk.logz.io:8071` and I think this is not yet supported.

Let me know if I can clarify anything more.

**Comment by ffmit** [comment]
Would you please explain why you think this is not supported? Is there any specific problem situation?

**Comment by fred-cardoso** [comment]
Because if you check [this](https://github.com/oanhnn/laravel-logzio/blob/51d5403fda289e99ff2727fb2eed1ed387eb7fb8/src/Log/Handler.php#L153) there is no option for a `uk` endpoint. That's all.
